// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4BmGjPLWWOYVqvELIfvnLMk-ugStBEI',
    appId: '1:969244227772:android:d482c690d7e3f12992f8b9',
    messagingSenderId: '969244227772',
    projectId: 'mindlist-c29f6',
    storageBucket: 'mindlist-c29f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLQ-hFEvgyCVKbU0VDCWZQliVpQ1qGs7U',
    appId: '1:969244227772:ios:181179a03502ca5d92f8b9',
    messagingSenderId: '969244227772',
    projectId: 'mindlist-c29f6',
    storageBucket: 'mindlist-c29f6.firebasestorage.app',
    androidClientId: '969244227772-02tfvgu3o88hqcp5p1eeosbvmne5o92h.apps.googleusercontent.com',
    iosClientId: '969244227772-71db8rk71vdpoev9m02gqcc5dhrf9v40.apps.googleusercontent.com',
    iosBundleId: 'com.armanmaurya.mindlist',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNSrlFuOJ5GwlTGVbQ-HZusr9xnKXOI-M',
    appId: '1:969244227772:web:9ff15cbaffb0ccba92f8b9',
    messagingSenderId: '969244227772',
    projectId: 'mindlist-c29f6',
    authDomain: 'mindlist-c29f6.firebaseapp.com',
    storageBucket: 'mindlist-c29f6.firebasestorage.app',
    measurementId: 'G-H5B15TZ3PK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLQ-hFEvgyCVKbU0VDCWZQliVpQ1qGs7U',
    appId: '1:969244227772:ios:6982ac506151969b92f8b9',
    messagingSenderId: '969244227772',
    projectId: 'mindlist-c29f6',
    storageBucket: 'mindlist-c29f6.firebasestorage.app',
    androidClientId: '969244227772-02tfvgu3o88hqcp5p1eeosbvmne5o92h.apps.googleusercontent.com',
    iosClientId: '969244227772-49plbpv59uj2nt8tu0k8818er8vh9h7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoNative',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNSrlFuOJ5GwlTGVbQ-HZusr9xnKXOI-M',
    appId: '1:969244227772:web:f0ee28fa367f0bed92f8b9',
    messagingSenderId: '969244227772',
    projectId: 'mindlist-c29f6',
    authDomain: 'mindlist-c29f6.firebaseapp.com',
    storageBucket: 'mindlist-c29f6.firebasestorage.app',
    measurementId: 'G-VPWMMHL4Z3',
  );

}